spring:
  datasource:
    url: jdbc:h2:mem:demo?characterEncoding=utf8?createDatabaseIfNotExist=true
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        format_sql: true
        show_sql: true
