insert into category(name)
values ('one category'),
       ('two category'),
       ('three category'),
       ('four category'),
       ('five category'),
       ('six category'),
       ('seven category'),
       ('eight category'),
       ('nine category'),
       ('ten category'),
       ('eleven category'),
       ('twelve category'),
       ('thirteen category'),
       ('fourteen category'),
       ('fifteen category'),
       ('sixteen category'),
       ('seventeen category'),
       ('eighteen category'),
       ('nineteen category'),
       ('twenty category'),
       ('twenty one category'),
       ('twenty two category'),
       ('twenty three category'),
       ('twenty four category'),
       ('twenty five category'),
       ('twenty six category'),
       ('twenty seven category'),
       ('twenty eight category'),
       ('twenty nine category'),
       ('thirty category'),
       ('thirty one category'),
       ('thirty two category'),
       ('thirty three category'),
       ('thirty four category'),
       ('th irty five category'),
       ('thirty six category'),
       ('thirty seven category'),
       ('thirty eight category'),
       ('thirty nine category'),
       ('fourty category'),
       ('fourty one category'),
       ('fourty two category'),
       ('fourty three category'),
       ('fourty four category'),
       ('fourty five category'),
       ('fourty six category'),
       ('fourty seven category'),
       ('fourty eight category'),
       ('fourty nine category'),
       ('fifty category'),
       ('fifty one category'),
       ('fifty two category'),
       ('fifty three category'),
       ('fifty four category'),
       ('fifty five category'),
       ('fifty six category'),
       ('fifty seven category'),
       ('fifty eight category'),
       ('fifty nine category'),
       ('sixty category'),
       ('sixty one category'),
       ('sixty two category'),
       ('sixty three category'),
       ('sixty four category'),
       ('sixty five category'),
       ('sixty six category'),
       ('sixty seven category'),
       ('sixty eight category'),
       ('sixty nine category'),
       ('seventy category'),
       ('seventy one category'),
       ('seventy two category'),
       ('seventy three category'),
       ('seventy four category'),
       ('seventy five category'),
       ('seventy six category'),
       ('seventy seven category'),
       ('seventy eight category'),
       ('seventy nine category'),
       ('eighty category'),
       ('eighty one category'),
       ('eighty two category'),
       ('eighty three category'),
       ('eighty four category'),
       ('eighty five category'),
       ('eighty six category'),
       ('eighty seven category'),
       ('eighty eight category'),
       ('eighty nine category'),
       ('ninety category'),
       ('ninety one category'),
       ('ninety two category'),
       ('ninety three category'),
       ('ninety four category'),
       ('ninety five category'),
       ('ninety six category'),
       ('ninety seven category'),
       ('ninety eight category'),
       ('ninety nine category'),
       ('one hundred category'),
       ('one hundred one category'),
       ('one hundred two category'),
       ('one hundred three category'),
       ('one hundred four category'),
       ('one hundred five category'),
       ('one hundred six category'),
       ('one hundred seven category'),
       ('one hundred eight category'),
       ('one hundred nine category'),
       ('one hundred ten category'),
       ('one hundred eleven category'),
       ('one hundred twelve category'),
       ('one hundred thirteen category'),
       ('one hundred fourteen category'),
       ('one hundred fifteen category'),
       ('one hundred sixteen category'),
       ('one hundred seventeen category'),
       ('one hundred eighteen category'),
       ('one hundred nineteen category'),
       ('one hundred twenty category'),
       ('one hundred twenty one category'),
       ('one hundred twenty two category'),
       ('one hundred twenty three category'),
       ('one hundred twenty four category'),
       ('one hundred twenty five category'),
       ('one hundred twenty six category'),
       ('one hundred twenty seven category'),
       ('one hundred twenty eight category'),
       ('one hundred twenty nine category'),
       ('one hundred thirty category'),
       ('one hundred thirty one category'),
       ('one hundred thirty two category'),
       ('one hundred thirty three category'),
       ('one hundred thirty four category'),
       ('one hundred thirty five category'),
       ('one hundred thirty six category'),
       ('one hundred thirty seven category'),
       ('one hundred thirty eight category'),
       ('one hundred thirty nine category'),
       ('one hundred fourty category'),
       ('one hundred fourty one category'),
       ('one hundred fourty two category'),
       ('one hundred fourty three category'),
       ('one hundred fourty four category'),
       ('one hundred fourty five category'),
       ('one hundred fourty six category'),
       ('one hundred fourty seven category'),
       ('one hundred fourty eight category'),
       ('one hundred fourty nine category'),
       ('one hundred fifty category'),
       ('one hundred fifty one category'),
       ('one hundred fifty two category'),
       ('one hundred fifty three category'),
       ('one hundred fifty four category'),
       ('one hundred fifty five category'),
       ('one hundred fifty six category'),
       ('one hundred fifty seven category'),
       ('one hundred fifty eight category'),
       ('one hundred fifty nine category'),
       ('one hundred sixty category'),
       ('one hundred sixty one category'),
       ('one hundred sixty two category'),
       ('one hundred sixty three category'),
       ('one hundred sixty four category'),
       ('one hundred sixty five category'),
       ('one hundred sixty six category'),
       ('one hundred sixty seven category'),
       ('one hundred sixty eight category'),
       ('one hundred sixty nine category'),
       ('one hundred seventy category'),
       ('one hundred seventy one category'),
       ('one hundred seventy two category'),
       ('one hundred seventy three category'),
       ('one hundred seventy four category'),
       ('one hundred seventy five category'),
       ('one hundred seventy six category'),
       ('one hundred seventy seven category'),
       ('one hundred seventy eight category'),
       ('one hundred seventy nine category'),
       ('one hundred eighty category'),
       ('one hundred eighty one category'),
       ('one hundred eighty two category'),
       ('one hundred eighty three category'),
       ('one hundred eighty four category'),
       ('one hundred eighty five category'),
       ('one hundred eighty six category'),
       ('one hundred eighty seven category'),
       ('one hundred eighty eight category'),
       ('one hundred eighty nine category'),
       ('one hundred ninety category'),
       ('one hundred ninety one category'),
       ('one hundred ninety two category'),
       ('one hundred ninety three category'),
       ('one hundred ninety four category'),
       ('one hundred ninety five category'),
       ('one hundred ninety six category'),
       ('one hundred ninety seven category'),
       ('one hundred ninety eight category'),
       ('one hundred ninety nine category'),
       ('two hundred category'),
       ('two hundred category'),
       ('two hundred one category'),
       ('two hundred two category'),
       ('two hundred three category'),
       ('two hundred four category'),
       ('two hundred five category'),
       ('two hundred six category'),
       ('two hundred seven category'),
       ('two hundred eight category'),
       ('two hundred nine category'),
       ('two hundred ten category'),
       ('two hundred eleven category'),
       ('two hundred twelve category'),
       ('two hundred thirteen category'),
       ('two hundred fourteen category'),
       ('two hundred fifteen category'),
       ('two hundred sixteen category'),
       ('two hundred seventeen category'),
       ('two hundred eighteen category'),
       ('two hundred nineteen category'),
       ('two hundred twenty category'),
       ('two hundred twenty one category'),
       ('two hundred twenty two category'),
       ('two hundred twenty three category'),
       ('two hundred twenty four category'),
       ('two hundred twenty five category'),
       ('two hundred twenty six category'),
       ('two hundred twenty seven category'),
       ('two hundred twenty eight category'),
       ('two hundred twenty nine category'),
       ('two hundred thirty category'),
       ('two hundred thirty one category'),
       ('two hundred thirty two category'),
       ('two hundred thirty three category'),
       ('two hundred thirty four category'),
       ('two hundred thirty five category'),
       ('two hundred thirty six category'),
       ('two hundred thirty seven category'),
       ('two hundred thirty eight category'),
       ('two hundred thirty nine category'),
       ('two hundred fourty category'),
       ('two hundred fourty one category'),
       ('two hundred fourty two category'),
       ('two hundred fourty three category'),
       ('two hundred fourty four category'),
       ('two hundred fourty five category'),
       ('two hundred fourty six category'),
       ('two hundred fourty seven category'),
       ('two hundred fourty eight category'),
       ('two hundred fourty nine category'),
       ('two hundred fifty category'),
       ('two hundred fifty one category'),
       ('two hundred fifty two category'),
       ('two hundred fifty three category'),
       ('two hundred fifty four category'),
       ('two hundred fifty five category'),
       ('two hundred fifty six category'),
       ('two hundred fifty seven category'),
       ('two hundred fifty eight category'),
       ('two hundred fifty nine category'),
       ('two hundred sixty category'),
       ('two hundred sixty one category'),
       ('two hundred sixty two category'),
       ('two hundred sixty three category'),
       ('two hundred sixty four category'),
       ('two hundred sixty five category'),
       ('two hundred sixty six category'),
       ('two hundred sixty seven category'),
       ('two hundred sixty eight category'),
       ('two hundred sixty nine category'),
       ('two hundred seventy category'),
       ('two hundred seventy one category'),
       ('two hundred seventy two category'),
       ('two hundred seventy three category'),
       ('two hundred seventy four category'),
       ('two hundred seventy five category'),
       ('two hundred seventy six category'),
       ('two hundred seventy seven category'),
       ('two hundred seventy eight category'),
       ('two hundred seventy nine category'),
       ('two hundred eighty category'),
       ('two hundred eighty one category'),
       ('two hundred eighty two category'),
       ('two hundred eighty three category'),
       ('two hundred eighty four category'),
       ('two hundred eighty five category'),
       ('two hundred eighty six category'),
       ('two hundred eighty seven category'),
       ('two hundred eighty eight category'),
       ('two hundred eighty nine category'),
       ('two hundred ninety category'),
       ('two hundred ninety one category'),
       ('two hundred ninety two category'),
       ('two hundred ninety three category'),
       ('two hundred ninety four category'),
       ('two hundred ninety five category'),
       ('two hundred ninety six category'),
       ('two hundred ninety seven category'),
       ('two hundred ninety eight category'),
       ('two hundred ninety nine category'),
       ('three hundred category'),
       ('three hundred category'),
       ('three hundred category'),
       ('three hundred one category'),
       ('three hundred two category'),
       ('three hundred three category'),
       ('three hundred four category'),
       ('three hundred five category'),
       ('three hundred six category'),
       ('three hundred seven category'),
       ('three hundred eight category'),
       ('three hundred nine category'),
       ('three hundred ten category'),
       ('three hundred eleven category'),
       ('three hundred twelve category'),
       ('three hundred thirteen category'),
       ('three hundred fourteen category'),
       ('three hundred fifteen category'),
       ('three hundred sixteen category'),
       ('three hundred seventeen category'),
       ('three hundred eighteen category'),
       ('three hundred nineteen category'),
       ('three hundred twenty category'),
       ('three hundred twenty one category'),
       ('three hundred twenty two category'),
       ('three hundred twenty three category'),
       ('three hundred twenty four category'),
       ('three hundred twenty five category'),
       ('three hundred twenty six category'),
       ('three hundred twenty seven category'),
       ('three hundred twenty eight category'),
       ('three hundred twenty nine category'),
       ('three hundred thirty category'),
       ('three hundred thirty one category'),
       ('three hundred thirty two category'),
       ('three hundred thirty three category'),
       ('three hundred thirty four category'),
       ('three hundred thirty five category'),
       ('three hundred thirty six category'),
       ('three hundred thirty seven category'),
       ('three hundred thirty eight category'),
       ('three hundred thirty nine category'),
       ('three hundred fourty category'),
       ('three hundred fourty one category'),
       ('three hundred fourty two category'),
       ('three hundred fourty three category'),
       ('three hundred fourty four category'),
       ('three hundred fourty five category'),
       ('three hundred fourty six category'),
       ('three hundred fourty seven category'),
       ('three hundred fourty eight category'),
       ('three hundred fourty nine category'),
       ('three hundred fifty category'),
       ('three hundred fifty one category'),
       ('three hundred fifty two category'),
       ('three hundred fifty three category'),
       ('three hundred fifty four category'),
       ('three hundred fifty five category'),
       ('three hundred fifty six category'),
       ('three hundred fifty seven category'),
       ('three hundred fifty eight category'),
       ('three hundred fifty nine category'),
       ('three hundred sixty category'),
       ('three hundred sixty one category'),
       ('three hundred sixty two category'),
       ('three hundred sixty three category'),
       ('three hundred sixty four category'),
       ('three hundred sixty five category'),
       ('three hundred sixty six category'),
       ('three hundred sixty seven category'),
       ('three hundred sixty eight category'),
       ('three hundred sixty nine category'),
       ('three hundred seventy category'),
       ('three hundred seventy one category'),
       ('three hundred seventy two category'),
       ('three hundred seventy three category'),
       ('three hundred seventy four category'),
       ('three hundred seventy five category'),
       ('three hundred seventy six category'),
       ('three hundred seventy seven category'),
       ('three hundred seventy eight category'),
       ('three hundred seventy nine category'),
       ('three hundred eighty category'),
       ('three hundred eighty one category'),
       ('three hundred eighty two category'),
       ('three hundred eighty three category'),
       ('three hundred eighty four category'),
       ('three hundred eighty five category'),
       ('three hundred eighty six category'),
       ('three hundred eighty seven category'),
       ('three hundred eighty eight category'),
       ('three hundred eighty nine category'),
       ('three hundred ninety category'),
       ('three hundred ninety one category'),
       ('three hundred ninety two category'),
       ('three hundred ninety three category'),
       ('three hundred ninety four category'),
       ('three hundred ninety five category'),
       ('three hundred ninety six category'),
       ('three hundred ninety seven category'),
       ('three hundred ninety eight category'),
       ('three hundred ninety nine category'),
       ('four hundred category'),
       ('four hundred category'),
       ('four hundred category'),
       ('four hundred category'),
       ('four hundred one category'),
       ('four hundred two category'),
       ('four hundred three category'),
       ('four hundred four category'),
       ('four hundred five category'),
       ('four hundred six category'),
       ('four hundred seven category'),
       ('four hundred eight category'),
       ('four hundred nine category'),
       ('four hundred ten category'),
       ('four hundred eleven category'),
       ('four hundred twelve category'),
       ('four hundred thirteen category'),
       ('four hundred fourteen category'),
       ('four hundred fifteen category'),
       ('four hundred sixteen category'),
       ('four hundred seventeen category'),
       ('four hundred eighteen category'),
       ('four hundred nineteen category'),
       ('four hundred twenty category'),
       ('four hundred twenty one category'),
       ('four hundred twenty two category'),
       ('four hundred twenty three category'),
       ('four hundred twenty four category'),
       ('four hundred twenty five category'),
       ('four hundred twenty six category'),
       ('four hundred twenty seven category'),
       ('four hundred twenty eight category'),
       ('four hundred twenty nine category'),
       ('four hundred thirty category'),
       ('four hundred thirty one category'),
       ('four hundred thirty two category'),
       ('four hundred thirty three category'),
       ('four hundred thirty four category'),
       ('four hundred thirty five category'),
       ('four hundred thirty six category'),
       ('four hundred thirty seven category'),
       ('four hundred thirty eight category'),
       ('four hundred thirty nine category'),
       ('four hundred fourty category'),
       ('four hundred fourty one category'),
       ('four hundred fourty two category'),
       ('four hundred fourty three category'),
       ('four hundred fourty four category'),
       ('four hundred fourty five category'),
       ('four hundred fourty six category'),
       ('four hundred fourty seven category'),
       ('four hundred fourty eight category'),
       ('four hundred fourty nine category'),
       ('four hundred fifty category'),
       ('four hundred fifty one category'),
       ('four hundred fifty two category'),
       ('four hundred fifty three category'),
       ('four hundred fifty four category'),
       ('four hundred fifty five category'),
       ('four hundred fifty six category'),
       ('four hundred fifty seven category'),
       ('four hundred fifty eight category'),
       ('four hundred fifty nine category'),
       ('four hundred sixty category'),
       ('four hundred sixty one category'),
       ('four hundred sixty two category'),
       ('four hundred sixty three category'),
       ('four hundred sixty four category'),
       ('four hundred sixty five category'),
       ('four hundred sixty six category'),
       ('four hundred sixty seven category'),
       ('four hundred sixty eight category'),
       ('four hundred sixty nine category'),
       ('four hundred seventy category'),
       ('four hundred seventy one category'),
       ('four hundred seventy two category'),
       ('four hundred seventy three category'),
       ('four hundred seventy four category'),
       ('four hundred seventy five category'),
       ('four hundred seventy six category'),
       ('four hundred seventy seven category'),
       ('four hundred seventy eight category'),
       ('four hundred seventy nine category'),
       ('four hundred eighty category'),
       ('four hundred eighty one category'),
       ('four hundred eighty two category'),
       ('four hundred eighty three category'),
       ('four hundred eighty four category'),
       ('four hundred eighty five category'),
       ('four hundred eighty six category'),
       ('four hundred eighty seven category'),
       ('four hundred eighty eight category'),
       ('four hundred eighty nine category'),
       ('four hundred ninety category'),
       ('four hundred ninety one category'),
       ('four hundred ninety two category'),
       ('four hundred ninety three category'),
       ('four hundred ninety four category'),
       ('four hundred ninety five category'),
       ('four hundred ninety six category'),
       ('four hundred ninety seven category'),
       ('four hundred ninety eight category'),
       ('four hundred ninety nine category'),
       ('five hundred category');

insert into user(first_Name, last_Name)
values ('one', 'user'),
       ('two', 'user'),
       ('three', 'user'),
       ('four', 'user'),
       ('five', 'user'),
       ('six', 'user'),
       ('seven', 'user'),
       ('eight', 'user'),
       ('nine', 'user'),
       ('ten', 'user'),
       ('eleven', 'user'),
       ('twelve', 'user'),
       ('thirteen', 'user'),
       ('fourteen', 'user'),
       ('fifteen', 'user'),
       ('sixteen', 'user'),
       ('seventeen', 'user'),
       ('eighteen', 'user'),
       ('nineteen', 'user'),
       ('twenty', 'user'),
       ('twenty one', 'user'),
       ('twenty two', 'user'),
       ('twenty three', 'user'),
       ('twenty four', 'user'),
       ('twenty five', 'user'),
       ('twenty six', 'user'),
       ('twenty seven', 'user'),
       ('twenty eight', 'user'),
       ('twenty nine', 'user'),
       ('thirty', 'user'),
       ('thirty one', 'user'),
       ('thirty two', 'user'),
       ('thirty three', 'user'),
       ('thirty four', 'user'),
       ('thirty five', 'user'),
       ('thirty six', 'user'),
       ('thirty seven', 'user'),
       ('thirty eight', 'user'),
       ('thirty nine', 'user'),
       ('fourty', 'user'),
       ('fourty one', 'user'),
       ('fourty two', 'user'),
       ('fourty three', 'user'),
       ('fourty four', 'user'),
       ('fourty five', 'user'),
       ('fourty six', 'user'),
       ('fourty seven', 'user'),
       ('fourty eight', 'user'),
       ('fourty nine', 'user'),
       ('fifty', 'user'),
       ('fifty one', 'user'),
       ('fifty two', 'user'),
       ('fifty three', 'user'),
       ('fifty four', 'user'),
       ('fifty five', 'user'),
       ('fifty six', 'user'),
       ('fifty seven', 'user'),
       ('fifty eight', 'user'),
       ('fifty nine', 'user'),
       ('sixty', 'user'),
       ('sixty one', 'user'),
       ('sixty two', 'user'),
       ('sixty three', 'user'),
       ('sixty four', 'user'),
       ('sixty five', 'user'),
       ('sixty six', 'user'),
       ('sixty seven', 'user'),
       ('sixty eight', 'user'),
       ('sixty nine', 'user'),
       ('seventy', 'user'),
       ('seventy one', 'user'),
       ('seventy two', 'user'),
       ('seventy three', 'user'),
       ('seventy four', 'user'),
       ('seventy five', 'user'),
       ('seventy six', 'user'),
       ('seventy seven', 'user'),
       ('seventy eight', 'user'),
       ('seventy nine', 'user'),
       ('eighty', 'user'),
       ('eighty one', 'user'),
       ('eighty two', 'user'),
       ('eighty three', 'user'),
       ('eighty four', 'user'),
       ('eighty five', 'user'),
       ('eighty six', 'user'),
       ('eighty seven', 'user'),
       ('eighty eight', 'user'),
       ('eighty nine', 'user'),
       ('ninety', 'user'),
       ('ninety one', 'user'),
       ('ninety two', 'user'),
       ('ninety three', 'user'),
       ('ninety four', 'user'),
       ('ninety five', 'user'),
       ('ninety six', 'user'),
       ('ninety seven', 'user'),
       ('ninety eight', 'user'),
       ('ninety nine', 'user'),
       ('one hundred', 'user'),
       ('one hundred one', 'user'),
       ('one hundred two', 'user'),
       ('one hundred three', 'user'),
       ('one hundred four', 'user'),
       ('one hundred five', 'user'),
       ('one hundred six', 'user'),
       ('one hundred seven', 'user'),
       ('one hundred eight', 'user'),
       ('one hundred nine', 'user'),
       ('one hundred ten', 'user'),
       ('one hundred eleven', 'user'),
       ('one hundred twelve', 'user'),
       ('one hundred thirteen', 'user'),
       ('one hundred fourteen', 'user'),
       ('one hundred fifteen', 'user'),
       ('one hundred sixteen', 'user'),
       ('one hundred seventeen', 'user'),
       ('one hundred eighteen', 'user'),
       ('one hundred nineteen', 'user'),
       ('one hundred twenty', 'user'),
       ('one hundred twenty one', 'user'),
       ('one hundred twenty two', 'user'),
       ('one hundred twenty three', 'user'),
       ('one hundred twenty four', 'user'),
       ('one hundred twenty five', 'user'),
       ('one hundred twenty six', 'user'),
       ('one hundred twenty seven', 'user'),
       ('one hundred twenty eight', 'user'),
       ('one hundred twenty nine', 'user'),
       ('one hundred thirty', 'user'),
       ('one hundred thirty one', 'user'),
       ('one hundred thirty two', 'user'),
       ('one hundred thirty three', 'user'),
       ('one hundred thirty four', 'user'),
       ('one hundred thirty five', 'user'),
       ('one hundred thirty six', 'user'),
       ('one hundred thirty seven', 'user'),
       ('one hundred thirty eight', 'user'),
       ('one hundred thirty nine', 'user'),
       ('one hundred fourty', 'user'),
       ('one hundred fourty one', 'user'),
       ('one hundred fourty two', 'user'),
       ('one hundred fourty three', 'user'),
       ('one hundred fourty four', 'user'),
       ('one hundred fourty five', 'user'),
       ('one hundred fourty six', 'user'),
       ('one hundred fourty seven', 'user'),
       ('one hundred fourty eight', 'user'),
       ('one hundred fourty nine', 'user'),
       ('one hundred fifty', 'user'),
       ('one hundred fifty one', 'user'),
       ('one hundred fifty two', 'user'),
       ('one hundred fifty three', 'user'),
       ('one hundred fifty four', 'user'),
       ('one hundred fifty five', 'user'),
       ('one hundred fifty six', 'user'),
       ('one hundred fifty seven', 'user'),
       ('one hundred fifty eight', 'user'),
       ('one hundred fifty nine', 'user'),
       ('one hundred sixty', 'user'),
       ('one hundred sixty one', 'user'),
       ('one hundred sixty two', 'user'),
       ('one hundred sixty three', 'user'),
       ('one hundred sixty four', 'user'),
       ('one hundred sixty five', 'user'),
       ('one hundred sixty six', 'user'),
       ('one hundred sixty seven', 'user'),
       ('one hundred sixty eight', 'user'),
       ('one hundred sixty nine', 'user'),
       ('one hundred seventy', 'user'),
       ('one hundred seventy one', 'user'),
       ('one hundred seventy two', 'user'),
       ('one hundred seventy three', 'user'),
       ('one hundred seventy four', 'user'),
       ('one hundred seventy five', 'user'),
       ('one hundred seventy six', 'user'),
       ('one hundred seventy seven', 'user'),
       ('one hundred seventy eight', 'user'),
       ('one hundred seventy nine', 'user'),
       ('one hundred eighty', 'user'),
       ('one hundred eighty one', 'user'),
       ('one hundred eighty two', 'user'),
       ('one hundred eighty three', 'user'),
       ('one hundred eighty four', 'user'),
       ('one hundred eighty five', 'user'),
       ('one hundred eighty six', 'user'),
       ('one hundred eighty seven', 'user'),
       ('one hundred eighty eight', 'user'),
       ('one hundred eighty nine', 'user'),
       ('one hundred ninety', 'user'),
       ('one hundred ninety one', 'user'),
       ('one hundred ninety two', 'user'),
       ('one hundred ninety three', 'user'),
       ('one hundred ninety four', 'user'),
       ('one hundred ninety five', 'user'),
       ('one hundred ninety six', 'user'),
       ('one hundred ninety seven', 'user'),
       ('one hundred ninety eight', 'user'),
       ('one hundred ninety nine', 'user'),
       ('two hundred', 'user'),
       ('two hundred one', 'user'),
       ('two hundred two', 'user'),
       ('two hundred three', 'user'),
       ('two hundred four', 'user'),
       ('two hundred five', 'user'),
       ('two hundred six', 'user'),
       ('two hundred seven', 'user'),
       ('two hundred eight', 'user'),
       ('two hundred nine', 'user'),
       ('two hundred ten', 'user'),
       ('two hundred eleven', 'user'),
       ('two hundred twelve', 'user'),
       ('two hundred thirteen', 'user'),
       ('two hundred fourteen', 'user'),
       ('two hundred fifteen', 'user'),
       ('two hundred sixteen', 'user'),
       ('two hundred seventeen', 'user'),
       ('two hundred eighteen', 'user'),
       ('two hundred nineteen', 'user'),
       ('two hundred twenty', 'user'),
       ('two hundred twenty one', 'user'),
       ('two hundred twenty two', 'user'),
       ('two hundred twenty three', 'user'),
       ('two hundred twenty four', 'user'),
       ('two hundred twenty five', 'user'),
       ('two hundred twenty six', 'user'),
       ('two hundred twenty seven', 'user'),
       ('two hundred twenty eight', 'user'),
       ('two hundred twenty nine', 'user'),
       ('two hundred thirty', 'user'),
       ('two hundred thirty one', 'user'),
       ('two hundred thirty two', 'user'),
       ('two hundred thirty three', 'user'),
       ('two hundred thirty four', 'user'),
       ('two hundred thirty five', 'user'),
       ('two hundred thirty six', 'user'),
       ('two hundred thirty seven', 'user'),
       ('two hundred thirty eight', 'user'),
       ('two hundred thirty nine', 'user'),
       ('two hundred fourty', 'user'),
       ('two hundred fourty one', 'user'),
       ('two hundred fourty two', 'user'),
       ('two hundred fourty three', 'user'),
       ('two hundred fourty four', 'user'),
       ('two hundred fourty five', 'user'),
       ('two hundred fourty six', 'user'),
       ('two hundred fourty seven', 'user'),
       ('two hundred fourty eight', 'user'),
       ('two hundred fourty nine', 'user'),
       ('two hundred fifty', 'user'),
       ('two hundred fifty one', 'user'),
       ('two hundred fifty two', 'user'),
       ('two hundred fifty three', 'user'),
       ('two hundred fifty four', 'user'),
       ('two hundred fifty five', 'user'),
       ('two hundred fifty six', 'user'),
       ('two hundred fifty seven', 'user'),
       ('two hundred fifty eight', 'user'),
       ('two hundred fifty nine', 'user'),
       ('two hundred sixty', 'user'),
       ('two hundred sixty one', 'user'),
       ('two hundred sixty two', 'user'),
       ('two hundred sixty three', 'user'),
       ('two hundred sixty four', 'user'),
       ('two hundred sixty five', 'user'),
       ('two hundred sixty six', 'user'),
       ('two hundred sixty seven', 'user'),
       ('two hundred sixty eight', 'user'),
       ('two hundred sixty nine', 'user'),
       ('two hundred seventy', 'user'),
       ('two hundred seventy one', 'user'),
       ('two hundred seventy two', 'user'),
       ('two hundred seventy three', 'user'),
       ('two hundred seventy four', 'user'),
       ('two hundred seventy five', 'user'),
       ('two hundred seventy six', 'user'),
       ('two hundred seventy seven', 'user'),
       ('two hundred seventy eight', 'user'),
       ('two hundred seventy nine', 'user'),
       ('two hundred eighty', 'user'),
       ('two hundred eighty one', 'user'),
       ('two hundred eighty two', 'user'),
       ('two hundred eighty three', 'user'),
       ('two hundred eighty four', 'user'),
       ('two hundred eighty five', 'user'),
       ('two hundred eighty six', 'user'),
       ('two hundred eighty seven', 'user'),
       ('two hundred eighty eight', 'user'),
       ('two hundred eighty nine', 'user'),
       ('two hundred ninety', 'user'),
       ('two hundred ninety one', 'user'),
       ('two hundred ninety two', 'user'),
       ('two hundred ninety three', 'user'),
       ('two hundred ninety four', 'user'),
       ('two hundred ninety five', 'user'),
       ('two hundred ninety six', 'user'),
       ('two hundred ninety seven', 'user'),
       ('two hundred ninety eight', 'user'),
       ('two hundred ninety nine', 'user'),
       ('three hundred', 'user'),
       ('three hundred one', 'user'),
       ('three hundred two', 'user'),
       ('three hundred three', 'user'),
       ('three hundred four', 'user'),
       ('three hundred five', 'user'),
       ('three hundred six', 'user'),
       ('three hundred seven', 'user'),
       ('three hundred eight', 'user'),
       ('three hundred nine', 'user'),
       ('three hundred ten', 'user'),
       ('three hundred eleven', 'user'),
       ('three hundred twelve', 'user'),
       ('three hundred thirteen', 'user'),
       ('three hundred fourteen', 'user'),
       ('three hundred fifteen', 'user'),
       ('three hundred sixteen', 'user'),
       ('three hundred seventeen', 'user'),
       ('three hundred eighteen', 'user'),
       ('three hundred nineteen', 'user'),
       ('three hundred twenty', 'user'),
       ('three hundred twenty one', 'user'),
       ('three hundred twenty two', 'user'),
       ('three hundred twenty three', 'user'),
       ('three hundred twenty four', 'user'),
       ('three hundred twenty five', 'user'),
       ('three hundred twenty six', 'user'),
       ('three hundred twenty seven', 'user'),
       ('three hundred twenty eight', 'user'),
       ('three hundred twenty nine', 'user'),
       ('three hundred thirty', 'user'),
       ('three hundred thirty one', 'user'),
       ('three hundred thirty two', 'user'),
       ('three hundred thirty three', 'user'),
       ('three hundred thirty four', 'user'),
       ('three hundred thirty five', 'user'),
       ('three hundred thirty six', 'user'),
       ('three hundred thirty seven', 'user'),
       ('three hundred thirty eight', 'user'),
       ('three hundred thirty nine', 'user'),
       ('three hundred fourty', 'user'),
       ('three hundred fourty one', 'user'),
       ('three hundred fourty two', 'user'),
       ('three hundred fourty three', 'user'),
       ('three hundred fourty four', 'user'),
       ('three hundred fourty five', 'user'),
       ('three hundred fourty six', 'user'),
       ('three hundred fourty seven', 'user'),
       ('three hundred fourty eight', 'user'),
       ('three hundred fourty nine', 'user'),
       ('three hundred fifty', 'user'),
       ('three hundred fifty one', 'user'),
       ('three hundred fifty two', 'user'),
       ('three hundred fifty three', 'user'),
       ('three hundred fifty four', 'user'),
       ('three hundred fifty five', 'user'),
       ('three hundred fifty six', 'user'),
       ('three hundred fifty seven', 'user'),
       ('three hundred fifty eight', 'user'),
       ('three hundred fifty nine', 'user'),
       ('three hundred sixty', 'user'),
       ('three hundred sixty one', 'user'),
       ('three hundred sixty two', 'user'),
       ('three hundred sixty three', 'user'),
       ('three hundred sixty four', 'user'),
       ('three hundred sixty five', 'user'),
       ('three hundred sixty six', 'user'),
       ('three hundred sixty seven', 'user'),
       ('three hundred sixty eight', 'user'),
       ('three hundred sixty nine', 'user'),
       ('three hundred seventy', 'user'),
       ('three hundred seventy one', 'user'),
       ('three hundred seventy two', 'user'),
       ('three hundred seventy three', 'user'),
       ('three hundred seventy four', 'user'),
       ('three hundred seventy five', 'user'),
       ('three hundred seventy six', 'user'),
       ('three hundred seventy seven', 'user'),
       ('three hundred seventy eight', 'user'),
       ('three hundred seventy nine', 'user'),
       ('three hundred eighty', 'user'),
       ('three hundred eighty one', 'user'),
       ('three hundred eighty two', 'user'),
       ('three hundred eighty three', 'user'),
       ('three hundred eighty four', 'user'),
       ('three hundred eighty five', 'user'),
       ('three hundred eighty six', 'user'),
       ('three hundred eighty seven', 'user'),
       ('three hundred eighty eight', 'user'),
       ('three hundred eighty nine', 'user'),
       ('three hundred ninety', 'user'),
       ('three hundred ninety one', 'user'),
       ('three hundred ninety two', 'user'),
       ('three hundred ninety three', 'user'),
       ('three hundred ninety four', 'user'),
       ('three hundred ninety five', 'user'),
       ('three hundred ninety six', 'user'),
       ('three hundred ninety seven', 'user'),
       ('three hundred ninety eight', 'user'),
       ('three hundred ninety nine', 'user'),
       ('four hundred', 'user'),
       ('four hundred one', 'user'),
       ('four hundred two', 'user'),
       ('four hundred three', 'user'),
       ('four hundred four', 'user'),
       ('four hundred five', 'user'),
       ('four hundred six', 'user'),
       ('four hundred seven', 'user'),
       ('four hundred eight', 'user'),
       ('four hundred nine', 'user'),
       ('four hundred ten', 'user'),
       ('four hundred eleven', 'user'),
       ('four hundred twelve', 'user'),
       ('four hundred thirteen', 'user'),
       ('four hundred fourteen', 'user'),
       ('four hundred fifteen', 'user'),
       ('four hundred sixteen', 'user'),
       ('four hundred seventeen', 'user'),
       ('four hundred eighteen', 'user'),
       ('four hundred nineteen', 'user'),
       ('four hundred twenty', 'user'),
       ('four hundred twenty one', 'user'),
       ('four hundred twenty two', 'user'),
       ('four hundred twenty three', 'user'),
       ('four hundred twenty four', 'user'),
       ('four hundred twenty five', 'user'),
       ('four hundred twenty six', 'user'),
       ('four hundred twenty seven', 'user'),
       ('four hundred twenty eight', 'user'),
       ('four hundred twenty nine', 'user'),
       ('four hundred thirty', 'user'),
       ('four hundred thirty one', 'user'),
       ('four hundred thirty two', 'user'),
       ('four hundred thirty three', 'user'),
       ('four hundred thirty four', 'user'),
       ('four hundred thirty five', 'user'),
       ('four hundred thirty six', 'user'),
       ('four hundred thirty seven', 'user'),
       ('four hundred thirty eight', 'user'),
       ('four hundred thirty nine', 'user'),
       ('four hundred fourty', 'user'),
       ('four hundred fourty one', 'user'),
       ('four hundred fourty two', 'user'),
       ('four hundred fourty three', 'user'),
       ('four hundred fourty four', 'user'),
       ('four hundred fourty five', 'user'),
       ('four hundred fourty six', 'user'),
       ('four hundred fourty seven', 'user'),
       ('four hundred fourty eight', 'user'),
       ('four hundred fourty nine', 'user'),
       ('four hundred fifty', 'user'),
       ('four hundred fifty one', 'user'),
       ('four hundred fifty two', 'user'),
       ('four hundred fifty three', 'user'),
       ('four hundred fifty four', 'user'),
       ('four hundred fifty five', 'user'),
       ('four hundred fifty six', 'user'),
       ('four hundred fifty seven', 'user'),
       ('four hundred fifty eight', 'user'),
       ('four hundred fifty nine', 'user'),
       ('four hundred sixty', 'user'),
       ('four hundred sixty one', 'user'),
       ('four hundred sixty two', 'user'),
       ('four hundred sixty three', 'user'),
       ('four hundred sixty four', 'user'),
       ('four hundred sixty five', 'user'),
       ('four hundred sixty six', 'user'),
       ('four hundred sixty seven', 'user'),
       ('four hundred sixty eight', 'user'),
       ('four hundred sixty nine', 'user'),
       ('four hundred seventy', 'user'),
       ('four hundred seventy one', 'user'),
       ('four hundred seventy two', 'user'),
       ('four hundred seventy three', 'user'),
       ('four hundred seventy four', 'user'),
       ('four hundred seventy five', 'user'),
       ('four hundred seventy six', 'user'),
       ('four hundred seventy seven', 'user'),
       ('four hundred seventy eight', 'user'),
       ('four hundred seventy nine', 'user'),
       ('four hundred eighty', 'user'),
       ('four hundred eighty one', 'user'),
       ('four hundred eighty two', 'user'),
       ('four hundred eighty three', 'user'),
       ('four hundred eighty four', 'user'),
       ('four hundred eighty five', 'user'),
       ('four hundred eighty six', 'user'),
       ('four hundred eighty seven', 'user'),
       ('four hundred eighty eight', 'user'),
       ('four hundred eighty nine', 'user'),
       ('four hundred ninety', 'user'),
       ('four hundred ninety one', 'user'),
       ('four hundred ninety two', 'user'),
       ('four hundred ninety three', 'user'),
       ('four hundred ninety four', 'user'),
       ('four hundred ninety five', 'user'),
       ('four hundred ninety six', 'user'),
       ('four hundred ninety seven', 'user'),
       ('four hundred ninety eight', 'user'),
       ('four hundred ninety nine', 'user'),
       ('five hundred', 'user');


insert into address(id, country, city)
values (1, 'Belarus', 'Minsk'),
       (2, 'Belarus', 'Minsk'),
       (3, 'Belarus', 'Minsk'),
       (4, 'Belarus', 'Minsk'),
       (5, 'Belarus', 'Minsk'),
       (6, 'Belarus', 'Minsk'),
       (7, 'Belarus', 'Minsk'),
       (8, 'Belarus', 'Minsk'),
       (9, 'Belarus', 'Minsk'),
       (10, 'Belarus', 'Minsk'),
       (11, 'Belarus', 'Minsk'),
       (12, 'Belarus', 'Minsk'),
       (13, 'Belarus', 'Minsk'),
       (14, 'Belarus', 'Minsk'),
       (15, 'Belarus', 'Minsk'),
       (16, 'Belarus', 'Minsk'),
       (17, 'Belarus', 'Minsk'),
       (18, 'Belarus', 'Minsk'),
       (19, 'Belarus', 'Minsk'),
       (20, 'Belarus', 'Minsk'),
       (21, 'Belarus', 'Minsk'),
       (22, 'Belarus', 'Minsk'),
       (23, 'Belarus', 'Minsk'),
       (24, 'Belarus', 'Minsk'),
       (25, 'Belarus', 'Minsk'),
       (26, 'Belarus', 'Minsk'),
       (27, 'Belarus', 'Minsk'),
       (28, 'Belarus', 'Minsk'),
       (29, 'Belarus', 'Minsk'),
       (30, 'Belarus', 'Minsk'),
       (31, 'Belarus', 'Minsk'),
       (32, 'Belarus', 'Minsk'),
       (33, 'Belarus', 'Minsk'),
       (34, 'Belarus', 'Minsk'),
       (35, 'Belarus', 'Minsk'),
       (36, 'Belarus', 'Minsk'),
       (37, 'Belarus', 'Minsk'),
       (38, 'Belarus', 'Minsk'),
       (39, 'Belarus', 'Minsk'),
       (40, 'Belarus', 'Minsk'),
       (41, 'Belarus', 'Minsk'),
       (42, 'Belarus', 'Minsk'),
       (43, 'Belarus', 'Minsk'),
       (44, 'Belarus', 'Minsk'),
       (45, 'Belarus', 'Minsk'),
       (46, 'Belarus', 'Minsk'),
       (47, 'Belarus', 'Minsk'),
       (48, 'Belarus', 'Minsk'),
       (49, 'Belarus', 'Minsk'),
       (50, 'Belarus', 'Minsk'),
       (51, 'Belarus', 'Minsk'),
       (52, 'Belarus', 'Minsk'),
       (53, 'Belarus', 'Minsk'),
       (54, 'Belarus', 'Minsk'),
       (55, 'Belarus', 'Minsk'),
       (56, 'Belarus', 'Minsk'),
       (57, 'Belarus', 'Minsk'),
       (58, 'Belarus', 'Minsk'),
       (59, 'Belarus', 'Minsk'),
       (60, 'Belarus', 'Minsk'),
       (61, 'Belarus', 'Minsk'),
       (62, 'Belarus', 'Minsk'),
       (63, 'Belarus', 'Minsk'),
       (64, 'Belarus', 'Minsk'),
       (65, 'Belarus', 'Minsk'),
       (66, 'Belarus', 'Minsk'),
       (67, 'Belarus', 'Minsk'),
       (68, 'Belarus', 'Minsk'),
       (69, 'Belarus', 'Minsk'),
       (70, 'Belarus', 'Minsk'),
       (71, 'Belarus', 'Minsk'),
       (72, 'Belarus', 'Minsk'),
       (73, 'Belarus', 'Minsk'),
       (74, 'Belarus', 'Minsk'),
       (75, 'Belarus', 'Minsk'),
       (76, 'Belarus', 'Minsk'),
       (77, 'Belarus', 'Minsk'),
       (78, 'Belarus', 'Minsk'),
       (79, 'Belarus', 'Minsk'),
       (80, 'Belarus', 'Minsk'),
       (81, 'Belarus', 'Minsk'),
       (82, 'Belarus', 'Minsk'),
       (83, 'Belarus', 'Minsk'),
       (84, 'Belarus', 'Minsk'),
       (85, 'Belarus', 'Minsk'),
       (86, 'Belarus', 'Minsk'),
       (87, 'Belarus', 'Minsk'),
       (88, 'Belarus', 'Minsk'),
       (89, 'Belarus', 'Minsk'),
       (90, 'Belarus', 'Minsk'),
       (91, 'Belarus', 'Minsk'),
       (92, 'Belarus', 'Minsk'),
       (93, 'Belarus', 'Minsk'),
       (94, 'Belarus', 'Minsk'),
       (95, 'Belarus', 'Minsk'),
       (96, 'Belarus', 'Minsk'),
       (97, 'Belarus', 'Minsk'),
       (98, 'Belarus', 'Minsk'),
       (99, 'Belarus', 'Minsk'),
       (100, 'Belarus', 'Mogilev'),
       (101, 'Belarus', 'Mogilev'),
       (102, 'Belarus', 'Mogilev'),
       (103, 'Belarus', 'Mogilev'),
       (104, 'Belarus', 'Mogilev'),
       (105, 'Belarus', 'Mogilev'),
       (106, 'Belarus', 'Mogilev'),
       (107, 'Belarus', 'Mogilev'),
       (108, 'Belarus', 'Mogilev'),
       (109, 'Belarus', 'Mogilev'),
       (110, 'Belarus', 'Mogilev'),
       (111, 'Belarus', 'Mogilev'),
       (112, 'Belarus', 'Mogilev'),
       (113, 'Belarus', 'Mogilev'),
       (114, 'Belarus', 'Mogilev'),
       (115, 'Belarus', 'Mogilev'),
       (116, 'Belarus', 'Mogilev'),
       (117, 'Belarus', 'Mogilev'),
       (118, 'Belarus', 'Mogilev'),
       (119, 'Belarus', 'Mogilev'),
       (120, 'Belarus', 'Mogilev'),
       (121, 'Belarus', 'Mogilev'),
       (122, 'Belarus', 'Mogilev'),
       (123, 'Belarus', 'Mogilev'),
       (124, 'Belarus', 'Mogilev'),
       (125, 'Belarus', 'Mogilev'),
       (126, 'Belarus', 'Mogilev'),
       (127, 'Belarus', 'Mogilev'),
       (128, 'Belarus', 'Mogilev'),
       (129, 'Belarus', 'Mogilev'),
       (130, 'Belarus', 'Mogilev'),
       (131, 'Belarus', 'Mogilev'),
       (132, 'Belarus', 'Mogilev'),
       (133, 'Belarus', 'Mogilev'),
       (134, 'Belarus', 'Mogilev'),
       (135, 'Belarus', 'Mogilev'),
       (136, 'Belarus', 'Mogilev'),
       (137, 'Belarus', 'Mogilev'),
       (138, 'Belarus', 'Mogilev'),
       (139, 'Belarus', 'Mogilev'),
       (140, 'Belarus', 'Mogilev'),
       (141, 'Belarus', 'Mogilev'),
       (142, 'Belarus', 'Mogilev'),
       (143, 'Belarus', 'Mogilev'),
       (144, 'Belarus', 'Mogilev'),
       (145, 'Belarus', 'Mogilev'),
       (146, 'Belarus', 'Mogilev'),
       (147, 'Belarus', 'Mogilev'),
       (148, 'Belarus', 'Mogilev'),
       (149, 'Belarus', 'Mogilev'),
       (150, 'Belarus', 'Mogilev'),
       (151, 'Belarus', 'Mogilev'),
       (152, 'Belarus', 'Mogilev'),
       (153, 'Belarus', 'Mogilev'),
       (154, 'Belarus', 'Mogilev'),
       (155, 'Belarus', 'Mogilev'),
       (156, 'Belarus', 'Mogilev'),
       (157, 'Belarus', 'Mogilev'),
       (158, 'Belarus', 'Mogilev'),
       (159, 'Belarus', 'Mogilev'),
       (160, 'Belarus', 'Mogilev'),
       (161, 'Belarus', 'Mogilev'),
       (162, 'Belarus', 'Mogilev'),
       (163, 'Belarus', 'Mogilev'),
       (164, 'Belarus', 'Mogilev'),
       (165, 'Belarus', 'Mogilev'),
       (166, 'Belarus', 'Mogilev'),
       (167, 'Belarus', 'Mogilev'),
       (168, 'Belarus', 'Mogilev'),
       (169, 'Belarus', 'Mogilev'),
       (170, 'Belarus', 'Mogilev'),
       (171, 'Belarus', 'Mogilev'),
       (172, 'Belarus', 'Mogilev'),
       (173, 'Belarus', 'Mogilev'),
       (174, 'Belarus', 'Mogilev'),
       (175, 'Belarus', 'Mogilev'),
       (176, 'Belarus', 'Mogilev'),
       (177, 'Belarus', 'Mogilev'),
       (178, 'Belarus', 'Mogilev'),
       (179, 'Belarus', 'Mogilev'),
       (180, 'Belarus', 'Mogilev'),
       (181, 'Belarus', 'Mogilev'),
       (182, 'Belarus', 'Mogilev'),
       (183, 'Belarus', 'Mogilev'),
       (184, 'Belarus', 'Mogilev'),
       (185, 'Belarus', 'Mogilev'),
       (186, 'Belarus', 'Mogilev'),
       (187, 'Belarus', 'Mogilev'),
       (188, 'Belarus', 'Mogilev'),
       (189, 'Belarus', 'Mogilev'),
       (190, 'Belarus', 'Mogilev'),
       (191, 'Belarus', 'Mogilev'),
       (192, 'Belarus', 'Mogilev'),
       (193, 'Belarus', 'Mogilev'),
       (194, 'Belarus', 'Mogilev'),
       (195, 'Belarus', 'Mogilev'),
       (196, 'Belarus', 'Mogilev'),
       (197, 'Belarus', 'Mogilev'),
       (198, 'Belarus', 'Mogilev'),
       (199, 'Belarus', 'Mogilev'),
       (200, 'Belarus', 'Mogilev'),
       (201, 'Belarus', 'Brest'),
       (202, 'Belarus', 'Brest'),
       (203, 'Belarus', 'Brest'),
       (204, 'Belarus', 'Brest'),
       (205, 'Belarus', 'Brest'),
       (206, 'Belarus', 'Brest'),
       (207, 'Belarus', 'Brest'),
       (208, 'Belarus', 'Brest'),
       (209, 'Belarus', 'Brest'),
       (210, 'Belarus', 'Brest'),
       (211, 'Belarus', 'Brest'),
       (212, 'Belarus', 'Brest'),
       (213, 'Belarus', 'Brest'),
       (214, 'Belarus', 'Brest'),
       (215, 'Belarus', 'Brest'),
       (216, 'Belarus', 'Brest'),
       (217, 'Belarus', 'Brest'),
       (218, 'Belarus', 'Brest'),
       (219, 'Belarus', 'Brest'),
       (220, 'Belarus', 'Brest'),
       (221, 'Belarus', 'Brest'),
       (222, 'Belarus', 'Brest'),
       (223, 'Belarus', 'Brest'),
       (224, 'Belarus', 'Brest'),
       (225, 'Belarus', 'Brest'),
       (226, 'Belarus', 'Brest'),
       (227, 'Belarus', 'Brest'),
       (228, 'Belarus', 'Brest'),
       (229, 'Belarus', 'Brest'),
       (230, 'Belarus', 'Brest'),
       (231, 'Belarus', 'Brest'),
       (232, 'Belarus', 'Brest'),
       (233, 'Belarus', 'Brest'),
       (234, 'Belarus', 'Brest'),
       (235, 'Belarus', 'Brest'),
       (236, 'Belarus', 'Brest'),
       (237, 'Belarus', 'Brest'),
       (238, 'Belarus', 'Brest'),
       (239, 'Belarus', 'Brest'),
       (240, 'Belarus', 'Brest'),
       (241, 'Belarus', 'Brest'),
       (242, 'Belarus', 'Brest'),
       (243, 'Belarus', 'Brest'),
       (244, 'Belarus', 'Brest'),
       (245, 'Belarus', 'Brest'),
       (246, 'Belarus', 'Brest'),
       (247, 'Belarus', 'Brest'),
       (248, 'Belarus', 'Brest'),
       (249, 'Belarus', 'Brest'),
       (250, 'Belarus', 'Brest'),
       (251, 'Belarus', 'Brest'),
       (252, 'Belarus', 'Brest'),
       (253, 'Belarus', 'Brest'),
       (254, 'Belarus', 'Brest'),
       (255, 'Belarus', 'Brest'),
       (256, 'Belarus', 'Brest'),
       (257, 'Belarus', 'Brest'),
       (258, 'Belarus', 'Brest'),
       (259, 'Belarus', 'Brest'),
       (260, 'Belarus', 'Brest'),
       (261, 'Belarus', 'Brest'),
       (262, 'Belarus', 'Brest'),
       (263, 'Belarus', 'Brest'),
       (264, 'Belarus', 'Brest'),
       (265, 'Belarus', 'Brest'),
       (266, 'Belarus', 'Brest'),
       (267, 'Belarus', 'Brest'),
       (268, 'Belarus', 'Brest'),
       (269, 'Belarus', 'Brest'),
       (270, 'Belarus', 'Brest'),
       (271, 'Belarus', 'Brest'),
       (272, 'Belarus', 'Brest'),
       (273, 'Belarus', 'Brest'),
       (274, 'Belarus', 'Brest'),
       (275, 'Belarus', 'Brest'),
       (276, 'Belarus', 'Brest'),
       (277, 'Belarus', 'Brest'),
       (278, 'Belarus', 'Brest'),
       (279, 'Belarus', 'Brest'),
       (280, 'Belarus', 'Brest'),
       (281, 'Belarus', 'Brest'),
       (282, 'Belarus', 'Brest'),
       (283, 'Belarus', 'Brest'),
       (284, 'Belarus', 'Brest'),
       (285, 'Belarus', 'Brest'),
       (286, 'Belarus', 'Brest'),
       (287, 'Belarus', 'Brest'),
       (288, 'Belarus', 'Brest'),
       (289, 'Belarus', 'Brest'),
       (290, 'Belarus', 'Brest'),
       (291, 'Belarus', 'Brest'),
       (292, 'Belarus', 'Brest'),
       (293, 'Belarus', 'Brest'),
       (294, 'Belarus', 'Brest'),
       (295, 'Belarus', 'Brest'),
       (296, 'Belarus', 'Brest'),
       (297, 'Belarus', 'Brest'),
       (298, 'Belarus', 'Brest'),
       (299, 'Belarus', 'Brest'),
       (300, 'Belarus', 'Brest'),
       (301, 'Belarus', 'Grodno'),
       (302, 'Belarus', 'Grodno'),
       (303, 'Belarus', 'Grodno'),
       (304, 'Belarus', 'Grodno'),
       (305, 'Belarus', 'Grodno'),
       (306, 'Belarus', 'Grodno'),
       (307, 'Belarus', 'Grodno'),
       (308, 'Belarus', 'Grodno'),
       (309, 'Belarus', 'Grodno'),
       (310, 'Belarus', 'Grodno'),
       (311, 'Belarus', 'Grodno'),
       (312, 'Belarus', 'Grodno'),
       (313, 'Belarus', 'Grodno'),
       (314, 'Belarus', 'Grodno'),
       (315, 'Belarus', 'Grodno'),
       (316, 'Belarus', 'Grodno'),
       (317, 'Belarus', 'Grodno'),
       (318, 'Belarus', 'Grodno'),
       (319, 'Belarus', 'Grodno'),
       (320, 'Belarus', 'Grodno'),
       (321, 'Belarus', 'Grodno'),
       (322, 'Belarus', 'Grodno'),
       (323, 'Belarus', 'Grodno'),
       (324, 'Belarus', 'Grodno'),
       (325, 'Belarus', 'Grodno'),
       (326, 'Belarus', 'Grodno'),
       (327, 'Belarus', 'Grodno'),
       (328, 'Belarus', 'Grodno'),
       (329, 'Belarus', 'Grodno'),
       (330, 'Belarus', 'Grodno'),
       (331, 'Belarus', 'Grodno'),
       (332, 'Belarus', 'Grodno'),
       (333, 'Belarus', 'Grodno'),
       (334, 'Belarus', 'Grodno'),
       (335, 'Belarus', 'Grodno'),
       (336, 'Belarus', 'Grodno'),
       (337, 'Belarus', 'Grodno'),
       (338, 'Belarus', 'Grodno'),
       (339, 'Belarus', 'Grodno'),
       (340, 'Belarus', 'Grodno'),
       (341, 'Belarus', 'Grodno'),
       (342, 'Belarus', 'Grodno'),
       (343, 'Belarus', 'Grodno'),
       (344, 'Belarus', 'Grodno'),
       (345, 'Belarus', 'Grodno'),
       (346, 'Belarus', 'Grodno'),
       (347, 'Belarus', 'Grodno'),
       (348, 'Belarus', 'Grodno'),
       (349, 'Belarus', 'Grodno'),
       (350, 'Belarus', 'Grodno'),
       (351, 'Belarus', 'Grodno'),
       (352, 'Belarus', 'Grodno'),
       (353, 'Belarus', 'Grodno'),
       (354, 'Belarus', 'Grodno'),
       (355, 'Belarus', 'Grodno'),
       (356, 'Belarus', 'Grodno'),
       (357, 'Belarus', 'Grodno'),
       (358, 'Belarus', 'Grodno'),
       (359, 'Belarus', 'Grodno'),
       (360, 'Belarus', 'Grodno'),
       (361, 'Belarus', 'Grodno'),
       (362, 'Belarus', 'Grodno'),
       (363, 'Belarus', 'Grodno'),
       (364, 'Belarus', 'Grodno'),
       (365, 'Belarus', 'Grodno'),
       (366, 'Belarus', 'Grodno'),
       (367, 'Belarus', 'Grodno'),
       (368, 'Belarus', 'Grodno'),
       (369, 'Belarus', 'Grodno'),
       (370, 'Belarus', 'Grodno'),
       (371, 'Belarus', 'Grodno'),
       (372, 'Belarus', 'Grodno'),
       (373, 'Belarus', 'Grodno'),
       (374, 'Belarus', 'Grodno'),
       (375, 'Belarus', 'Grodno'),
       (376, 'Belarus', 'Grodno'),
       (377, 'Belarus', 'Grodno'),
       (378, 'Belarus', 'Grodno'),
       (379, 'Belarus', 'Grodno'),
       (380, 'Belarus', 'Grodno'),
       (381, 'Belarus', 'Grodno'),
       (382, 'Belarus', 'Grodno'),
       (383, 'Belarus', 'Grodno'),
       (384, 'Belarus', 'Grodno'),
       (385, 'Belarus', 'Grodno'),
       (386, 'Belarus', 'Grodno'),
       (387, 'Belarus', 'Grodno'),
       (388, 'Belarus', 'Grodno'),
       (389, 'Belarus', 'Grodno'),
       (390, 'Belarus', 'Grodno'),
       (391, 'Belarus', 'Grodno'),
       (392, 'Belarus', 'Grodno'),
       (393, 'Belarus', 'Grodno'),
       (394, 'Belarus', 'Grodno'),
       (395, 'Belarus', 'Grodno'),
       (396, 'Belarus', 'Grodno'),
       (397, 'Belarus', 'Grodno'),
       (398, 'Belarus', 'Grodno'),
       (399, 'Belarus', 'Grodno'),
       (400, 'Belarus', 'Grodno'),
       (401, 'Belarus', 'Gomel'),
       (402, 'Belarus', 'Gomel'),
       (403, 'Belarus', 'Gomel'),
       (404, 'Belarus', 'Gomel'),
       (405, 'Belarus', 'Gomel'),
       (406, 'Belarus', 'Gomel'),
       (407, 'Belarus', 'Gomel'),
       (408, 'Belarus', 'Gomel'),
       (409, 'Belarus', 'Gomel'),
       (410, 'Belarus', 'Gomel'),
       (411, 'Belarus', 'Gomel'),
       (412, 'Belarus', 'Gomel'),
       (413, 'Belarus', 'Gomel'),
       (414, 'Belarus', 'Gomel'),
       (415, 'Belarus', 'Gomel'),
       (416, 'Belarus', 'Gomel'),
       (417, 'Belarus', 'Gomel'),
       (418, 'Belarus', 'Gomel'),
       (419, 'Belarus', 'Gomel'),
       (420, 'Belarus', 'Gomel'),
       (421, 'Belarus', 'Gomel'),
       (422, 'Belarus', 'Gomel'),
       (423, 'Belarus', 'Gomel'),
       (424, 'Belarus', 'Gomel'),
       (425, 'Belarus', 'Gomel'),
       (426, 'Belarus', 'Gomel'),
       (427, 'Belarus', 'Gomel'),
       (428, 'Belarus', 'Gomel'),
       (429, 'Belarus', 'Gomel'),
       (430, 'Belarus', 'Gomel'),
       (431, 'Belarus', 'Gomel'),
       (432, 'Belarus', 'Gomel'),
       (433, 'Belarus', 'Gomel'),
       (434, 'Belarus', 'Gomel'),
       (435, 'Belarus', 'Gomel'),
       (436, 'Belarus', 'Gomel'),
       (437, 'Belarus', 'Gomel'),
       (438, 'Belarus', 'Gomel'),
       (439, 'Belarus', 'Gomel'),
       (440, 'Belarus', 'Gomel'),
       (441, 'Belarus', 'Gomel'),
       (442, 'Belarus', 'Gomel'),
       (443, 'Belarus', 'Gomel'),
       (444, 'Belarus', 'Gomel'),
       (445, 'Belarus', 'Gomel'),
       (446, 'Belarus', 'Gomel'),
       (447, 'Belarus', 'Gomel'),
       (448, 'Belarus', 'Gomel'),
       (449, 'Belarus', 'Gomel'),
       (450, 'Belarus', 'Gomel'),
       (451, 'Belarus', 'Gomel'),
       (452, 'Belarus', 'Gomel'),
       (453, 'Belarus', 'Gomel'),
       (454, 'Belarus', 'Gomel'),
       (455, 'Belarus', 'Gomel'),
       (456, 'Belarus', 'Gomel'),
       (457, 'Belarus', 'Gomel'),
       (458, 'Belarus', 'Gomel'),
       (459, 'Belarus', 'Gomel'),
       (460, 'Belarus', 'Gomel'),
       (461, 'Belarus', 'Gomel'),
       (462, 'Belarus', 'Gomel'),
       (463, 'Belarus', 'Gomel'),
       (464, 'Belarus', 'Gomel'),
       (465, 'Belarus', 'Gomel'),
       (466, 'Belarus', 'Gomel'),
       (467, 'Belarus', 'Gomel'),
       (468, 'Belarus', 'Gomel'),
       (469, 'Belarus', 'Gomel'),
       (470, 'Belarus', 'Gomel'),
       (471, 'Belarus', 'Gomel'),
       (472, 'Belarus', 'Gomel'),
       (473, 'Belarus', 'Gomel'),
       (474, 'Belarus', 'Gomel'),
       (475, 'Belarus', 'Gomel'),
       (476, 'Belarus', 'Gomel'),
       (477, 'Belarus', 'Gomel'),
       (478, 'Belarus', 'Gomel'),
       (479, 'Belarus', 'Gomel'),
       (480, 'Belarus', 'Gomel'),
       (481, 'Belarus', 'Gomel'),
       (482, 'Belarus', 'Gomel'),
       (483, 'Belarus', 'Gomel'),
       (484, 'Belarus', 'Gomel'),
       (485, 'Belarus', 'Gomel'),
       (486, 'Belarus', 'Gomel'),
       (487, 'Belarus', 'Gomel'),
       (488, 'Belarus', 'Gomel'),
       (489, 'Belarus', 'Gomel'),
       (490, 'Belarus', 'Gomel'),
       (491, 'Belarus', 'Gomel'),
       (492, 'Belarus', 'Gomel'),
       (493, 'Belarus', 'Gomel'),
       (494, 'Belarus', 'Gomel'),
       (495, 'Belarus', 'Gomel'),
       (496, 'Belarus', 'Gomel'),
       (497, 'Belarus', 'Gomel'),
       (498, 'Belarus', 'Gomel'),
       (499, 'Belarus', 'Gomel'),
       (500, 'Belarus', 'Gomel');

insert into image(name, user_id)
values ('one image', 1),
       ('two image', 2),
       ('three image', 3),
       ('four image', 4),
       ('five image', 5),
       ('six image', 6),
       ('seven image', 7),
       ('eight image', 8),
       ('nine image', 9),
       ('ten image', 2),
       ('eleven image', 2),
       ('twelve image', 2),
       ('thirteen image', 2),
       ('fourteen image', 2),
       ('fifteen image', 2),
       ('sixteen image', 2),
       ('seventeen image', 2),
       ('eighteen image', 2),
       ('nineteen image', 2),
       ('twenty image', 2),
       ('twenty one image', 3),
       ('twenty two image', 3),
       ('twenty three image', 3),
       ('twenty four image', 3),
       ('twenty five image', 3),
       ('twenty six image', 3),
       ('twenty seven image', 3),
       ('twenty eight image', 3),
       ('twenty nine image', 3),
       ('thirty image', 3),
       ('thirty one image', 3),
       ('thirty two image', 3),
       ('thirty three image', 3),
       ('thirty four image', 3),
       ('thirty five image', 3),
       ('thirty six image', 3),
       ('thirty seven image', 3),
       ('thirty eight image', 3),
       ('thirty nine image', 3),
       ('fourty image', 3),
       ('fourty one image', 3),
       ('fourty two image', 3),
       ('fourty three image', 3),
       ('fourty four image', 3),
       ('fourty five image', 3),
       ('fourty six image', 3),
       ('fourty seven image', 3),
       ('fourty eight image', 3),
       ('fourty nine image', 3),
       ('fifty image', 3),
       ('fifty one image', 3),
       ('fifty two image', 3),
       ('fifty three image', 3),
       ('fifty four image', 3),
       ('fifty five image', 3),
       ('fifty six image', 3),
       ('fifty seven image', 3),
       ('fifty eight image', 3),
       ('fifty nine image', 3),
       ('sixty image', 3),
       ('sixty one image', 3),
       ('sixty two image', 3),
       ('sixty three image', 3),
       ('sixty four image', 3),
       ('sixty five image', 3),
       ('sixty six image', 3),
       ('sixty seven image', 3),
       ('sixty eight image', 3),
       ('sixty nine image', 3),
       ('seventy image', 3),
       ('seventy one image', 3),
       ('seventy two image', 3),
       ('seventy three image', 3),
       ('seventy four image', 3),
       ('seventy five image', 3),
       ('seventy six image', 3),
       ('seventy seven image', 3),
       ('seventy eight image', 3),
       ('seventy nine image', 3),
       ('eighty image', 3),
       ('eighty one image', 3),
       ('eighty two image', 3),
       ('eighty three image', 3),
       ('eighty four image', 3),
       ('eighty five image', 3),
       ('eighty six image', 3),
       ('eighty seven image', 3),
       ('eighty eight image', 3),
       ('eighty nine image', 3),
       ('ninety image', 3),
       ('ninety one image', 3),
       ('ninety two image', 3),
       ('ninety three image', 3),
       ('ninety four image', 3),
       ('ninety five image', 3),
       ('ninety six image', 3),
       ('ninety seven image', 3),
       ('ninety eight image', 3),
       ('ninety nine image', 3),
       ('one hundred image', 3),
       ('one hundred one image', 3),
       ('one hundred two image', 3),
       ('one hundred three image', 3),
       ('one hundred four image', 3),
       ('one hundred five image', 3),
       ('one hundred six image', 3),
       ('one hundred seven image', 3),
       ('one hundred eight image', 3),
       ('one hundred nine image', 3),
       ('one hundred ten image', 4),
       ('one hundred eleven image', 4),
       ('one hundred twelve image', 4),
       ('one hundred thirteen image', 4),
       ('one hundred fourteen image', 4),
       ('one hundred fifteen image', 4),
       ('one hundred sixteen image', 4),
       ('one hundred seventeen image', 4),
       ('one hundred eighteen image', 4),
       ('one hundred nineteen image', 4),
       ('one hundred twenty image', 4),
       ('one hundred twenty one image', 4),
       ('one hundred twenty two image', 4),
       ('one hundred twenty three image', 4),
       ('one hundred twenty four image', 4),
       ('one hundred twenty five image', 4),
       ('one hundred twenty six image', 4),
       ('one hundred twenty seven image', 4),
       ('one hundred twenty eight image', 4),
       ('one hundred twenty nine image', 4),
       ('one hundred thirty image', 4),
       ('one hundred thirty one image', 4),
       ('one hundred thirty two image', 4),
       ('one hundred thirty three image', 4),
       ('one hundred thirty four image', 4),
       ('one hundred thirty five image', 4),
       ('one hundred thirty six image', 4),
       ('one hundred thirty seven image', 4),
       ('one hundred thirty eight image', 4),
       ('one hundred thirty nine image', 4),
       ('one hundred fourty image', 4),
       ('one hundred fourty one image', 4),
       ('one hundred fourty two image', 4),
       ('one hundred fourty three image', 4),
       ('one hundred fourty four image', 4),
       ('one hundred fourty five image', 4),
       ('one hundred fourty six image', 4),
       ('one hundred fourty seven image', 4),
       ('one hundred fourty eight image', 4),
       ('one hundred fourty nine image', 4),
       ('one hundred fifty image', 4),
       ('one hundred fifty one image', 4),
       ('one hundred fifty two image', 4),
       ('one hundred fifty three image', 4),
       ('one hundred fifty four image', 4),
       ('one hundred fifty five image', 4),
       ('one hundred fifty six image', 4),
       ('one hundred fifty seven image', 4),
       ('one hundred fifty eight image', 4),
       ('one hundred fifty nine image', 4),
       ('one hundred sixty image', 4),
       ('one hundred sixty one image', 4),
       ('one hundred sixty two image', 4),
       ('one hundred sixty three image', 4),
       ('one hundred sixty four image', 4),
       ('one hundred sixty five image', 4),
       ('one hundred sixty six image', 4),
       ('one hundred sixty seven image', 4),
       ('one hundred sixty eight image', 4),
       ('one hundred sixty nine image', 4),
       ('one hundred seventy image', 4),
       ('one hundred seventy one image', 4),
       ('one hundred seventy two image', 4),
       ('one hundred seventy three image', 4),
       ('one hundred seventy four image', 4),
       ('one hundred seventy five image', 4),
       ('one hundred seventy six image', 4),
       ('one hundred seventy seven image', 4),
       ('one hundred seventy eight image', 4),
       ('one hundred seventy nine image', 4),
       ('one hundred eighty image', 4),
       ('one hundred eighty one image', 4),
       ('one hundred eighty two image', 4),
       ('one hundred eighty three image', 4),
       ('one hundred eighty four image', 4),
       ('one hundred eighty five image', 4),
       ('one hundred eighty six image', 4),
       ('one hundred eighty seven image', 4),
       ('one hundred eighty eight image', 4),
       ('one hundred eighty nine image', 4),
       ('one hundred ninety image', 4),
       ('one hundred ninety one image', 4),
       ('one hundred ninety two image', 4),
       ('one hundred ninety three image', 4),
       ('one hundred ninety four image', 4),
       ('one hundred ninety five image', 4),
       ('one hundred ninety six image', 4),
       ('one hundred ninety seven image', 4),
       ('one hundred ninety eight image', 4),
       ('one hundred ninety nine image', 4),
       ('two hundred image', 5),
       ('two hundred one image', 5),
       ('two hundred two image', 5),
       ('two hundred three image', 5),
       ('two hundred four image', 5),
       ('two hundred five image', 5),
       ('two hundred six image', 5),
       ('two hundred seven image', 5),
       ('two hundred eight image', 5),
       ('two hundred nine image', 5),
       ('two hundred ten image', 5),
       ('two hundred eleven image', 5),
       ('two hundred twelve image', 5),
       ('two hundred thirteen image', 5),
       ('two hundred fourteen image', 5),
       ('two hundred fifteen image', 5),
       ('two hundred sixteen image', 5),
       ('two hundred seventeen image', 5),
       ('two hundred eighteen image', 5),
       ('two hundred nineteen image', 5),
       ('two hundred twenty image', 5),
       ('two hundred twenty one image', 5),
       ('two hundred twenty two image', 5),
       ('two hundred twenty three image', 5),
       ('two hundred twenty four image', 5),
       ('two hundred twenty five image', 5),
       ('two hundred twenty six image', 5),
       ('two hundred twenty seven image', 5),
       ('two hundred twenty eight image', 5),
       ('two hundred twenty nine image', 5),
       ('two hundred thirty image', 5),
       ('two hundred thirty one image', 5),
       ('two hundred thirty two image', 5),
       ('two hundred thirty three image', 5),
       ('two hundred thirty four image', 5),
       ('two hundred thirty five image', 5),
       ('two hundred thirty six image', 5),
       ('two hundred thirty seven image', 5),
       ('two hundred thirty eight image', 5),
       ('two hundred thirty nine image', 5),
       ('two hundred fourty image', 5),
       ('two hundred fourty one image', 5),
       ('two hundred fourty two image', 5),
       ('two hundred fourty three image', 5),
       ('two hundred fourty four image', 5),
       ('two hundred fourty five image', 5),
       ('two hundred fourty six image', 5),
       ('two hundred fourty seven image', 5),
       ('two hundred fourty eight image', 5),
       ('two hundred fourty nine image', 5),
       ('two hundred fifty image', 5),
       ('two hundred fifty one image', 5),
       ('two hundred fifty two image', 5),
       ('two hundred fifty three image', 5),
       ('two hundred fifty four image', 5),
       ('two hundred fifty five image', 5),
       ('two hundred fifty six image', 5),
       ('two hundred fifty seven image', 5),
       ('two hundred fifty eight image', 5),
       ('two hundred fifty nine image', 5),
       ('two hundred sixty image', 5),
       ('two hundred sixty one image', 5),
       ('two hundred sixty two image', 5),
       ('two hundred sixty three image', 5),
       ('two hundred sixty four image', 5),
       ('two hundred sixty five image', 5),
       ('two hundred sixty six image', 5),
       ('two hundred sixty seven image', 5),
       ('two hundred sixty eight image', 5),
       ('two hundred sixty nine image', 5),
       ('two hundred seventy image', 5),
       ('two hundred seventy one image', 5),
       ('two hundred seventy two image', 5),
       ('two hundred seventy three image', 5),
       ('two hundred seventy four image', 5),
       ('two hundred seventy five image', 5),
       ('two hundred seventy six image', 5),
       ('two hundred seventy seven image', 5),
       ('two hundred seventy eight image', 5),
       ('two hundred seventy nine image', 5),
       ('two hundred eighty image', 5),
       ('two hundred eighty one image', 5),
       ('two hundred eighty two image', 5),
       ('two hundred eighty three image', 5),
       ('two hundred eighty four image', 5),
       ('two hundred eighty five image', 5),
       ('two hundred eighty six image', 5),
       ('two hundred eighty seven image', 5),
       ('two hundred eighty eight image', 5),
       ('two hundred eighty nine image', 5),
       ('two hundred ninety image', 5),
       ('two hundred ninety one image', 5),
       ('two hundred ninety two image', 5),
       ('two hundred ninety three image', 5),
       ('two hundred ninety four image', 5),
       ('two hundred ninety five image', 5),
       ('two hundred ninety six image', 5),
       ('two hundred ninety seven image', 5),
       ('two hundred ninety eight image', 5),
       ('two hundred ninety nine image', 5),
       ('three hundred image', 5),
       ('three hundred one image', 5),
       ('three hundred two image', 5),
       ('three hundred three image', 5),
       ('three hundred four image', 5),
       ('three hundred five image', 5),
       ('three hundred six image', 5),
       ('three hundred seven image', 5),
       ('three hundred eight image', 5),
       ('three hundred nine image', 5),
       ('three hundred ten image', 5),
       ('three hundred eleven image', 5),
       ('three hundred twelve image', 5),
       ('three hundred thirteen image', 5),
       ('three hundred fourteen image', 5),
       ('three hundred fifteen image', 5),
       ('three hundred sixteen image', 5),
       ('three hundred seventeen image', 5),
       ('three hundred eighteen image', 5),
       ('three hundred nineteen image', 5),
       ('three hundred twenty image', 5),
       ('three hundred twenty one image', 5),
       ('three hundred twenty two image', 5),
       ('three hundred twenty three image', 5),
       ('three hundred twenty four image', 5),
       ('three hundred twenty five image', 5),
       ('three hundred twenty six image', 5),
       ('three hundred twenty seven image', 5),
       ('three hundred twenty eight image', 5),
       ('three hundred twenty nine image', 5),
       ('three hundred thirty image', 5),
       ('three hundred thirty one image', 5),
       ('three hundred thirty two image', 5),
       ('three hundred thirty three image', 5),
       ('three hundred thirty four image', 5),
       ('three hundred thirty five image', 5),
       ('three hundred thirty six image', 5),
       ('three hundred thirty seven image', 5),
       ('three hundred thirty eight image', 5),
       ('three hundred thirty nine image', 5),
       ('three hundred fourty image', 6),
       ('three hundred fourty one image', 6),
       ('three hundred fourty two image', 6),
       ('three hundred fourty three image', 6),
       ('three hundred fourty four image', 6),
       ('three hundred fourty five image', 6),
       ('three hundred fourty six image', 6),
       ('three hundred fourty seven image', 6),
       ('three hundred fourty eight image', 6),
       ('three hundred fourty nine image', 6),
       ('three hundred fifty image', 6),
       ('three hundred fifty one image', 6),
       ('three hundred fifty two image', 6),
       ('three hundred fifty three image', 6),
       ('three hundred fifty four image', 6),
       ('three hundred fifty five image', 6),
       ('three hundred fifty six image', 6),
       ('three hundred fifty seven image', 6),
       ('three hundred fifty eight image', 6),
       ('three hundred fifty nine image', 6),
       ('three hundred sixty image', 6),
       ('three hundred sixty one image', 6),
       ('three hundred sixty two image', 6),
       ('three hundred sixty three image', 6),
       ('three hundred sixty four image', 6),
       ('three hundred sixty five image', 6),
       ('three hundred sixty six image', 6),
       ('three hundred sixty seven image', 6),
       ('three hundred sixty eight image', 6),
       ('three hundred sixty nine image', 6),
       ('three hundred seventy image', 6),
       ('three hundred seventy one image', 6),
       ('three hundred seventy two image', 6),
       ('three hundred seventy three image', 6),
       ('three hundred seventy four image', 6),
       ('three hundred seventy five image', 6),
       ('three hundred seventy six image', 6),
       ('three hundred seventy seven image', 6),
       ('three hundred seventy eight image', 6),
       ('three hundred seventy nine image', 6),
       ('three hundred eighty image', 6),
       ('three hundred eighty one image', 6),
       ('three hundred eighty two image', 6),
       ('three hundred eighty three image', 6),
       ('three hundred eighty four image', 6),
       ('three hundred eighty five image', 6),
       ('three hundred eighty six image', 6),
       ('three hundred eighty seven image', 6),
       ('three hundred eighty eight image', 6),
       ('three hundred eighty nine image', 6),
       ('three hundred ninety image', 6),
       ('three hundred ninety one image', 6),
       ('three hundred ninety two image', 6),
       ('three hundred ninety three image', 6),
       ('three hundred ninety four image', 6),
       ('three hundred ninety five image', 6),
       ('three hundred ninety six image', 6),
       ('three hundred ninety seven image', 6),
       ('three hundred ninety eight image', 6),
       ('three hundred ninety nine image', 6),
       ('four hundred image', 6),
       ('four hundred one image', 6),
       ('four hundred two image', 6),
       ('four hundred three image', 6),
       ('four hundred four image', 6),
       ('four hundred five image', 6),
       ('four hundred six image', 6),
       ('four hundred seven image', 6),
       ('four hundred eight image', 6),
       ('four hundred nine image', 6),
       ('four hundred ten image', 6),
       ('four hundred eleven image', 6),
       ('four hundred twelve image', 6),
       ('four hundred thirteen image', 6),
       ('four hundred fourteen image', 6),
       ('four hundred fifteen image', 6),
       ('four hundred sixteen image', 6),
       ('four hundred seventeen image', 6),
       ('four hundred eighteen image', 6),
       ('four hundred nineteen image', 6),
       ('four hundred twenty image', 6),
       ('four hundred twenty one image', 6),
       ('four hundred twenty two image', 6),
       ('four hundred twenty three image', 6),
       ('four hundred twenty four image', 6),
       ('four hundred twenty five image', 6),
       ('four hundred twenty six image', 6),
       ('four hundred twenty seven image', 6),
       ('four hundred twenty eight image', 6),
       ('four hundred twenty nine image', 6),
       ('four hundred thirty image', 7),
       ('four hundred thirty one image', 7),
       ('four hundred thirty two image', 7),
       ('four hundred thirty three image', 7),
       ('four hundred thirty four image', 7),
       ('four hundred thirty five image', 7),
       ('four hundred thirty six image', 7),
       ('four hundred thirty seven image', 7),
       ('four hundred thirty eight image', 7),
       ('four hundred thirty nine image', 7),
       ('four hundred fourty image', 7),
       ('four hundred fourty one image', 7),
       ('four hundred fourty two image', 7),
       ('four hundred fourty three image', 7),
       ('four hundred fourty four image', 7),
       ('four hundred fourty five image', 7),
       ('four hundred fourty six image', 7),
       ('four hundred fourty seven image', 7),
       ('four hundred fourty eight image', 7),
       ('four hundred fourty nine image', 7),
       ('four hundred fifty image', 7),
       ('four hundred fifty one image', 7),
       ('four hundred fifty two image', 7),
       ('four hundred fifty three image', 7),
       ('four hundred fifty four image', 7),
       ('four hundred fifty five image', 7),
       ('four hundred fifty six image', 7),
       ('four hundred fifty seven image', 7),
       ('four hundred fifty eight image', 7),
       ('four hundred fifty nine image', 7),
       ('four hundred sixty image', 7),
       ('four hundred sixty one image', 7),
       ('four hundred sixty two image', 7),
       ('four hundred sixty three image', 7),
       ('four hundred sixty four image', 7),
       ('four hundred sixty five image', 7),
       ('four hundred sixty six image', 7),
       ('four hundred sixty seven image', 7),
       ('four hundred sixty eight image', 7),
       ('four hundred sixty nine image', 7),
       ('four hundred seventy image', 7),
       ('four hundred seventy one image', 7),
       ('four hundred seventy two image', 7),
       ('four hundred seventy three image', 7),
       ('four hundred seventy four image', 7),
       ('four hundred seventy five image', 7),
       ('four hundred seventy six image', 7),
       ('four hundred seventy seven image', 7),
       ('four hundred seventy eight image', 7),
       ('four hundred seventy nine image', 7),
       ('four hundred eighty image', 7),
       ('four hundred eighty one image', 7),
       ('four hundred eighty two image', 7),
       ('four hundred eighty three image', 7),
       ('four hundred eighty four image', 7),
       ('four hundred eighty five image', 7),
       ('four hundred eighty six image', 7),
       ('four hundred eighty seven image', 7),
       ('four hundred eighty eight image', 7),
       ('four hundred eighty nine image', 7),
       ('four hundred ninety image', 7),
       ('four hundred ninety one image', 7),
       ('four hundred ninety two image', 7),
       ('four hundred ninety three image', 7),
       ('four hundred ninety four image', 7),
       ('four hundred ninety five image', 7),
       ('four hundred ninety six image', 7),
       ('four hundred ninety seven image', 7),
       ('four hundred ninety eight image', 7),
       ('four hundred ninety nine image', 7),
       ('five hundred image', 7);

insert into image_category(image_id, category_id)
values (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 10),
       (1, 11),
       (1, 12),
       (1, 13),
       (1, 14),
       (1, 15),
       (1, 31),
       (1, 32),
       (1, 33),
       (1, 34),
       (1, 35),
       (1, 36),
       (1, 37),
       (1, 38),
       (1, 39),
       (1, 40),
       (1, 41),
       (1, 42),
       (1, 43),
       (1, 44),
       (1, 45),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (2, 9),
       (2, 10),
       (2, 11),
       (2, 12),
       (2, 13),
       (2, 14),
       (2, 15),
       (2, 16),
       (2, 17),
       (2, 18),
       (2, 19),
       (2, 20),
       (2, 21),
       (2, 22),
       (2, 23),
       (2, 24),
       (2, 25),
       (2, 26),
       (2, 27),
       (2, 28),
       (2, 29),
       (2, 30),
       (3, 1),
       (4, 2),
       (5, 3),
       (6, 4),
       (7, 5),
       (8, 6),
       (9, 7),
       (10, 8),
       (11, 9),
       (12, 10),
       (13, 11),
       (14, 12),
       (15, 13),
       (16, 14),
       (17, 15),
       (18, 31),
       (19, 32),
       (20, 33),
       (21, 34),
       (22, 35),
       (23, 36),
       (24, 37),
       (25, 38),
       (26, 39),
       (27, 40),
       (28, 41),
       (29, 42),
       (30, 43),
       (40, 44),
       (41, 45),
       (42, 1),
       (43, 2),
       (44, 3),
       (45, 4),
       (46, 5),
       (47, 6),
       (48, 7),
       (49, 8),
       (50, 9),
       (51, 10),
       (52, 11),
       (52, 12),
       (54, 13),
       (55, 14),
       (56, 15),
       (57, 16),
       (58, 17),
       (59, 18),
       (60, 19),
       (61, 20),
       (62, 21),
       (63, 22),
       (64, 23),
       (65, 24),
       (66, 25),
       (67, 26),
       (68, 27),
       (69, 28),
       (70, 29),
       (71, 30),
       (72, 30),
       (73, 30),
       (74, 30),
       (75, 30),
       (76, 30),
       (77, 30),
       (78, 30),
       (79, 30),
       (81, 30),
       (82, 30),
       (83, 30),
       (84, 30),
       (85, 30),
       (86, 30),
       (87, 30),
       (88, 30),
       (89, 30),
       (90, 30),
       (91, 34),
       (92, 35),
       (93, 36),
       (94, 37),
       (95, 38),
       (96, 39),
       (97, 40),
       (98, 41),
       (99, 42),
       (90, 43),
       (90, 44),
       (100, 45),
       (101, 30),
       (102, 30),
       (103, 1),
       (104, 2),
       (105, 3),
       (106, 4),
       (107, 5),
       (108, 6),
       (109, 7),
       (110, 8),
       (111, 9),
       (112, 10),
       (113, 11),
       (114, 12),
       (115, 13),
       (116, 14),
       (117, 15),
       (118, 31),
       (119, 32),
       (120, 33),
       (121, 34),
       (122, 35),
       (123, 36),
       (124, 37),
       (125, 38),
       (126, 39),
       (127, 40),
       (128, 41),
       (129, 42),
       (130, 43),
       (131, 43),
       (132, 43),
       (133, 43),
       (134, 43),
       (135, 43),
       (136, 43),
       (137, 43),
       (138, 43),
       (139, 43),
       (140, 44),
       (141, 45),
       (142, 1),
       (143, 2),
       (144, 3),
       (145, 4),
       (146, 5),
       (147, 6),
       (148, 7),
       (149, 8),
       (150, 9),
       (151, 10),
       (152, 11),
       (153, 12),
       (154, 13),
       (155, 14),
       (156, 15),
       (157, 16),
       (158, 17),
       (159, 18),
       (160, 19),
       (161, 20),
       (162, 21),
       (163, 22),
       (164, 23),
       (165, 24),
       (166, 25),
       (167, 26),
       (168, 27),
       (169, 28),
       (170, 29),
       (171, 30),
       (172, 30),
       (173, 30),
       (174, 30),
       (175, 30),
       (176, 30),
       (177, 30),
       (178, 30),
       (179, 30),
       (180, 30),
       (181, 30),
       (182, 30),
       (183, 30),
       (184, 30),
       (185, 30),
       (186, 30),
       (187, 30),
       (188, 30),
       (189, 30),
       (190, 30),
       (191, 34),
       (192, 35),
       (193, 36),
       (194, 37),
       (195, 38),
       (196, 39),
       (197, 40),
       (198, 41),
       (199, 42),
       (200, 45),
       (201, 30),
       (202, 30),
       (203, 1),
       (204, 2),
       (205, 3),
       (206, 4),
       (207, 5),
       (208, 6),
       (209, 7),
       (210, 8),
       (211, 9),
       (212, 10),
       (213, 11),
       (214, 12),
       (215, 13),
       (216, 14),
       (217, 15),
       (218, 31),
       (219, 32),
       (220, 33),
       (221, 34),
       (222, 35),
       (223, 36),
       (224, 37),
       (225, 38),
       (226, 39),
       (227, 40),
       (228, 41),
       (229, 42),
       (230, 43),
       (231, 43),
       (232, 43),
       (233, 43),
       (234, 43),
       (235, 43),
       (236, 43),
       (237, 43),
       (238, 43),
       (239, 43),
       (240, 44),
       (241, 45),
       (242, 1),
       (243, 2),
       (244, 3),
       (245, 4),
       (246, 5),
       (247, 6),
       (248, 7),
       (249, 8),
       (250, 9),
       (251, 10),
       (252, 11),
       (253, 12),
       (254, 13),
       (255, 14),
       (256, 15),
       (257, 16),
       (258, 17),
       (259, 28),
       (260, 19),
       (261, 20),
       (262, 21),
       (263, 22),
       (264, 23),
       (265, 24),
       (266, 25),
       (267, 26),
       (268, 27),
       (269, 28),
       (270, 29),
       (271, 30),
       (272, 30),
       (273, 30),
       (274, 30),
       (275, 30),
       (276, 30),
       (277, 30),
       (278, 30),
       (279, 30),
       (280, 30),
       (281, 30),
       (282, 30),
       (283, 30),
       (284, 30),
       (285, 30),
       (286, 30),
       (287, 30),
       (288, 30),
       (289, 30),
       (290, 30),
       (291, 34),
       (292, 35),
       (293, 36),
       (294, 37),
       (295, 38),
       (296, 39),
       (297, 40),
       (298, 41),
       (299, 42),
       (300, 42),
       (301, 30),
       (302, 30),
       (303, 1),
       (304, 2),
       (305, 3),
       (306, 4),
       (307, 5),
       (308, 6),
       (309, 7),
       (310, 8),
       (311, 9),
       (312, 10),
       (313, 11),
       (314, 12),
       (315, 13),
       (316, 14),
       (317, 15),
       (318, 31),
       (319, 32),
       (320, 33),
       (321, 34),
       (332, 35),
       (323, 36),
       (324, 37),
       (325, 38),
       (326, 39),
       (327, 40),
       (328, 41),
       (329, 42),
       (330, 43),
       (331, 43),
       (332, 43),
       (333, 43),
       (334, 43),
       (335, 43),
       (336, 43),
       (337, 43),
       (338, 43),
       (339, 43),
       (340, 44),
       (341, 45),
       (342, 1),
       (343, 3),
       (344, 3),
       (345, 4),
       (346, 5),
       (347, 6),
       (348, 7),
       (349, 8),
       (350, 9),
       (351, 10),
       (352, 11),
       (353, 12),
       (354, 13),
       (355, 14),
       (356, 15),
       (357, 16),
       (358, 17),
       (359, 28),
       (360, 19),
       (361, 20),
       (362, 21),
       (363, 22),
       (364, 23),
       (365, 24),
       (366, 25),
       (367, 26),
       (368, 27),
       (369, 28),
       (370, 29),
       (371, 30),
       (372, 30),
       (373, 30),
       (374, 30),
       (375, 30),
       (376, 30),
       (377, 30),
       (378, 30),
       (379, 30),
       (380, 30),
       (381, 30),
       (382, 30),
       (383, 30),
       (384, 30),
       (385, 30),
       (386, 30),
       (387, 30),
       (388, 30),
       (389, 30),
       (390, 30),
       (391, 34),
       (392, 35),
       (393, 36),
       (394, 37),
       (395, 38),
       (396, 39),
       (397, 40),
       (398, 41),
       (399, 42),
       (400, 42),
       (401, 30),
       (402, 30),
       (403, 1),
       (404, 2),
       (405, 3),
       (406, 4),
       (407, 5),
       (408, 6),
       (409, 7),
       (410, 8),
       (411, 9),
       (412, 10),
       (413, 11),
       (414, 12),
       (415, 13),
       (416, 14),
       (417, 15),
       (418, 31),
       (419, 32),
       (420, 33),
       (421, 34),
       (432, 35),
       (423, 36),
       (424, 37),
       (425, 38),
       (426, 39),
       (427, 40),
       (428, 41),
       (429, 42),
       (430, 43),
       (431, 43),
       (432, 43),
       (433, 43),
       (434, 43),
       (435, 43),
       (436, 43),
       (437, 43),
       (438, 43),
       (439, 43),
       (440, 44),
       (441, 45),
       (442, 1),
       (443, 3),
       (444, 3),
       (445, 4),
       (446, 5),
       (447, 6),
       (448, 7),
       (449, 8),
       (450, 9),
       (451, 10),
       (452, 11),
       (453, 12),
       (454, 13),
       (455, 14),
       (456, 15),
       (457, 16),
       (458, 17),
       (459, 28),
       (460, 19),
       (461, 20),
       (462, 21),
       (463, 22),
       (464, 23),
       (465, 24),
       (466, 25),
       (467, 26),
       (468, 27),
       (469, 28),
       (470, 29),
       (471, 30),
       (472, 30),
       (473, 30),
       (474, 30),
       (475, 30),
       (476, 30),
       (477, 30),
       (478, 30),
       (479, 30),
       (480, 30),
       (481, 30),
       (482, 30),
       (483, 30),
       (484, 30),
       (485, 30),
       (486, 30),
       (487, 30),
       (488, 30),
       (489, 30),
       (490, 30),
       (491, 34),
       (492, 35),
       (493, 36),
       (494, 37),
       (495, 38),
       (496, 39),
       (497, 40),
       (498, 41),
       (499, 42),
       (500, 42);
